### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by serenity4** [JuliaGL/XCB.jl#12]
I would like to deploy some initial online documentation, but for this a `DOCUMENTER_KEY` variable must be set, as described in [the Documenter docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh). I currently don't have the permissions to add such a key, so would it be possible for someone with the right accesses to do that?

**Comment by SimonDanisch** [comment]
![image](https://user-images.githubusercontent.com/1010467/99719621-d61e8d00-2aac-11eb-9fbf-1e8615a4493d.png)

**Comment by serenity4** [comment]
Thanks! Sorry to reopen that, but I got an access denied error. Did you also add the public key?

![image](https://user-images.githubusercontent.com/38345285/99723052-ec7b1780-2ab1-11eb-904c-a02625c178a7.png)

**Comment by serenity4** [comment]
@SimonDanisch Could you please add the public key if you did not already? It might fix it. Thanks!

**Comment by SimonDanisch** [comment]
For what do you actually need that? I think I set that for travis, but I see that travis isn't even used :D 
Should the repository switch to github-actions? I think that's what's widely used now for all Julia packages, and I think you don't even need to setup any keys!

**Comment by SimonDanisch** [comment]
GLMakie shows how to setup xvfb to open windows: https://github.com/JuliaPlots/GLMakie.jl/blob/master/.github/workflows/ci.yml

**Comment by serenity4** [comment]
Yes, I think we should switch to github-actions. I already pushed some workflows for documentation `.github/workflows/Documenter.yml` and for testing `.github/workflows/Test.yml`. Everything works fine with xvfb (so far), I have yet to fake inputs to actually test stuff (for now it loops forever because we never give it input, I'm working on it).

As for Documenter, it is used with a SSH deploy key, but it has trouble fetching the repo:

![image](https://user-images.githubusercontent.com/38345285/103221805-c9028280-4923-11eb-9ab4-c3b92e15469d.png)

And from the error, it seems that we do need a public key along with the private key. From the repos I've been working on it has always been the case. Maybe authentication can be done with a Github Actions token, but apparently [it does not build gh-pages](https://github.com/JuliaDocs/Documenter.jl/issues/1177).

Also, is there a way to retrigger a build? I can do it on my repos, but not here, so I can't test whether Documenter works without pushing a new commit.

**Comment by serenity4** [comment]
@SimonDanisch could you please try to re-generate the private key and the public key via
```julia
using DocumenterTools
DocumenterTools.genkeys()
```

to try to solve this issue? By re-reading the error message I posted above, the very first line actually indicates an invalid format.

**Comment by SimonDanisch** [comment]
Ok, hopefully this time:
![image](https://user-images.githubusercontent.com/1010467/110618006-98965a80-8196-11eb-8e66-670244d00f25.png)
