### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by serenity4** [JuliaGL/XCB.jl#7]
I just saw that the package was not registered. I believe it is ready enough to be registered.

@JuliaRegistrator `register`

**Comment by serenity4** [comment]
@JuliaRegistrator register()

**Comment by fingolfin** [comment]
Your registry request was not accepted; you may wish to look at https://github.com/JuliaRegistries/General/pull/23401 which explains why.

**Comment by serenity4** [comment]
I am not finding the explanation in the link you provided; where exactly should I look?
Is it because of #9? Then the situation was resolved, this XCB.jl package supersedes Xcb.jl and should go on for registration.

**Comment by fingolfin** [comment]
Name does not meet all of the following: starts with an uppercase letter, ASCII alphanumerics only, not all letters are uppercase.
Name is not at least five characters long
The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: CEnum
Package name similar to 11 existing packages.

**Comment by fingolfin** [comment]
That's a (badly formatted quote from https://github.com/JuliaRegistries/General/pull/23401.

If you insist on the package name, you'll have to contact a human to convince them to make an exception (which might be easy, no idea; it's simply that the automated system won't accept it without a human override).

**Comment by serenity4** [comment]
I'd prefer to keep the name, since it wraps the existing XCB library. @SimonDanisch do you agree?
Who should I contact? Should I just leave a message in the Slack (pkg-registration) channel?

**Comment by fingolfin** [comment]
Note that the name is not the only issue

**Comment by SimonDanisch** [comment]
I think you can just answer on the General PR.
I think `XCB.jl` makes the most sense, and should be ok via the naming conventions, as it wraps that library.
If there's already a registered package named `Xcb.jl` that would be harder to resolve :D

**Comment by serenity4** [comment]
> Note that the name is not the only issue

I added a compat entry for CEnum, so this should already be resolved

**Comment by serenity4** [comment]
@JuliaRegistrator `register`
