### ISSUE TITLE
Comparison to https://gitlab.com/poposca/Xcb.jl ?

### ISSUE THREAD

**Issue by fingolfin** [JuliaGL/XCB.jl#9]
I just noticed both this package and https://gitlab.com/poposca/Xcb.jl and wonder if you folks might not want to join efforts instead of duplicating them?

**Comment by serenity4** [comment]
I contacted the author and he said that this repository is suitable to his need, and more advanced. Therefore I believe the situation is resolved, in favor of JuliaGL/XCB.jl.
